version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run: ya
    - run: date
    - run: ls
    - run: bot
    - run: top


workflows:
  version: 2
  abas:
    jobs:
    - abas
